import type { LiveAcceptanceCase } from "./live-acceptance";

const checked = "source_independently_checked" as const;
const unverified = "unverified" as const;

/**
 * Representative public boards. Source labels are review inputs, not observations made by the
 * harness. Role counts deliberately remain null until a person counts a dated snapshot.
 */
export const LIVE_ACCEPTANCE_CASES: LiveAcceptanceCase[] = [
  { id: "anduril", company: "Anduril", homepageUrl: "https://www.anduril.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/andurilindustries" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Board mapping is documented in REVIEW-PLAN; current count is time-dependent.", sourceEvidenceUrls: ["https://www.anduril.com/careers", "https://job-boards.greenhouse.io/andurilindustries"], sourceCheckedAt: "2026-09-20" },
  { id: "airbnb", company: "Airbnb", homepageUrl: "https://www.airbnb.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/airbnb" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source; independent dated review still required." },
  { id: "stripe", company: "Stripe", homepageUrl: "https://stripe.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/stripe" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source; independent dated review still required." },
  { id: "openai", company: "OpenAI", homepageUrl: "https://openai.com", expectedSource: { type: "html", url: "https://openai.com/careers/search/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "OpenAI's first-party careers page links to its first-party search listing; the previous Ashby candidate was stale.", sourceEvidenceUrls: ["https://openai.com/careers/", "https://openai.com/careers/search/"], sourceCheckedAt: "2026-09-20" },
  { id: "notion", company: "Notion", homepageUrl: "https://www.notion.so", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/notion" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Notion's first-party careers page links its roles to the Notion Ashby board.", sourceEvidenceUrls: ["https://www.notion.com/careers", "https://jobs.ashbyhq.com/notion"], sourceCheckedAt: "2026-09-20" },
  { id: "anthropic", company: "Anthropic", homepageUrl: "https://www.anthropic.com", expectedSource: { type: "greenhouse", url: "https://job-boards.greenhouse.io/anthropic" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Anthropic's first-party jobs listing links each live role to its Greenhouse board.", sourceEvidenceUrls: ["https://www.anthropic.com/careers", "https://www.anthropic.com/jobs", "https://job-boards.greenhouse.io/anthropic"], sourceCheckedAt: "2026-09-20" },
  { id: "netflix", company: "Netflix", homepageUrl: "https://www.netflix.com", expectedSource: { type: "lever", url: "https://jobs.lever.co/netflix" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source for live probing; independent source review still required." },
  { id: "figma", company: "Figma", homepageUrl: "https://www.figma.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/figma" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Figma's first-party careers page links its roles to the Figma Greenhouse board.", sourceEvidenceUrls: ["https://www.figma.com/careers/", "https://job-boards.greenhouse.io/figma"], sourceCheckedAt: "2026-09-20" },
  { id: "datadog", company: "Datadog", homepageUrl: "https://www.datadoghq.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/datadog" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source; independent dated review still required." },
  { id: "cloudflare", company: "Cloudflare", homepageUrl: "https://www.cloudflare.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/cloudflare" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source; independent source review still required." },
  { id: "canonical", company: "Canonical", homepageUrl: "https://canonical.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/canonical" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Canonical's first-party careers page links its roles to the Canonical Greenhouse board.", sourceEvidenceUrls: ["https://canonical.com/careers", "https://job-boards.greenhouse.io/canonical"], sourceCheckedAt: "2026-09-20" },
  { id: "automattic", company: "Automattic", homepageUrl: "https://automattic.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/automattic" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source; independent source review still required." },
  { id: "gitlab", company: "GitLab", homepageUrl: "https://about.gitlab.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/gitlab" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source; independent source review still required." },
  { id: "wise", company: "Wise", homepageUrl: "https://wise.com", expectedSource: { type: "html", url: "https://wise.jobs/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Wise's explicit first-party all-jobs listing is a SmartRecruiters Attrax-powered custom HTML site, not Workday or the SmartRecruiters public postings API.", sourceEvidenceUrls: ["https://wise.jobs", "https://wise.jobs/jobs"], sourceCheckedAt: "2026-09-20" },
  { id: "salesforce", company: "Salesforce", homepageUrl: "https://www.salesforce.com", expectedSource: { type: "workday", url: "https://salesforce.wd12.myworkdayjobs.com/External_Career_Site" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Workday tenant candidate; expected mapping requires independent review." },
  { id: "siemens", company: "Siemens", homepageUrl: "https://www.siemens.com", expectedSource: { type: "workday", url: "https://jobs.siemens.com/careers" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Enterprise custom-domain candidate; source type and mapping require independent review." },
  { id: "spotify", company: "Spotify", homepageUrl: "https://www.spotify.com", expectedSource: { type: "html", url: "https://www.lifeatspotify.com/jobs" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate first-party listing; independent dated review still required." },
  { id: "mozilla", company: "Mozilla", homepageUrl: "https://www.mozilla.org", expectedSource: { type: "html", url: "https://www.mozilla.org/en-US/careers/listings/" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "First-party listing candidate; independent review still required." },
  { id: "basecamp", company: "37signals", homepageUrl: "https://37signals.com", expectedSource: { type: "html", url: "https://37signals.com/jobs" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "First-party listing candidate; independent review still required." },
  { id: "monzo", company: "Monzo", homepageUrl: "https://monzo.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/monzo" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Monzo's first-party careers page links to the Monzo Greenhouse board.", sourceEvidenceUrls: ["https://monzo.com/careers", "https://boards.greenhouse.io/monzo"], sourceCheckedAt: "2026-09-20" },
  { id: "revolut", company: "Revolut", homepageUrl: "https://www.revolut.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/revolut" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source; independent source review still required." },
  { id: "zapier", company: "Zapier", homepageUrl: "https://zapier.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/zapier" }, expectedRoleCount: null, labelStatus: unverified, labelNote: "Candidate source; independent source review still required." },
  { id: "linear", company: "Linear", homepageUrl: "https://linear.app", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/Linear" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Linear's first-party careers listing links its roles to the Linear Ashby board.", sourceEvidenceUrls: ["https://linear.app/careers", "https://jobs.ashbyhq.com/Linear"], sourceCheckedAt: "2026-09-20" },
  { id: "vercel", company: "Vercel", homepageUrl: "https://vercel.com", expectedSource: { type: "greenhouse", url: "https://job-boards.greenhouse.io/vercel" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Vercel's first-party careers page links its roles to the Vercel Greenhouse board; the earlier Ashby candidate was stale.", sourceEvidenceUrls: ["https://vercel.com/careers", "https://job-boards.greenhouse.io/vercel"], sourceCheckedAt: "2026-09-20" },
  { id: "render", company: "Render", homepageUrl: "https://render.com", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/render" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Render's first-party careers page links its roles to the Render Ashby board.", sourceEvidenceUrls: ["https://render.com/careers", "https://jobs.ashbyhq.com/render"], sourceCheckedAt: "2026-09-20" },
];
