import type { LiveAcceptanceCase } from "./live-acceptance";

const checked = "source_independently_checked" as const;

/**
 * Representative public boards. Source labels are review inputs, not observations made by the
 * harness. Role counts deliberately remain null until a person counts a dated snapshot.
 */
export const LIVE_ACCEPTANCE_CASES: LiveAcceptanceCase[] = [
  { id: "anduril", company: "Anduril", homepageUrl: "https://www.anduril.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/andurilindustries" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Board mapping is documented in REVIEW-PLAN; current count is time-dependent.", sourceEvidenceUrls: ["https://www.anduril.com/careers", "https://job-boards.greenhouse.io/andurilindustries"], sourceCheckedAt: "2026-09-20" },
  { id: "airbnb", company: "Airbnb", homepageUrl: "https://www.airbnb.com", expectedSource: { type: "html", url: "https://careers.airbnb.com/positions/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Airbnb's first-party careers homepage links to its company-owned all-jobs listing; the previous Greenhouse board candidate was stale.", sourceEvidenceUrls: ["https://careers.airbnb.com/", "https://careers.airbnb.com/positions/"], sourceCheckedAt: "2026-09-20" },
  { id: "stripe", company: "Stripe", homepageUrl: "https://stripe.com", expectedSource: { type: "html", url: "https://stripe.com/careers/search" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Stripe's first-party careers page links to its current searchable listing at /careers/search; the previous Greenhouse board and /jobs/search candidates were stale.", sourceEvidenceUrls: ["https://stripe.com/careers", "https://stripe.com/careers/search"], sourceCheckedAt: "2026-09-20", coverage: { customHtml: { evidenceUrl: "https://stripe.com/careers/search", checkedAt: "2026-09-29", note: "First-party searchable HTML listing required guarded browser pagination; retained 63-page capture in SOURCE-BROWSER-CAPTURE-REPORT.md." } } },
  { id: "openai", company: "OpenAI", homepageUrl: "https://openai.com", expectedSource: { type: "html", url: "https://openai.com/careers/search/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "OpenAI's first-party careers page links to its first-party search listing; the previous Ashby candidate was stale.", sourceEvidenceUrls: ["https://openai.com/careers/", "https://openai.com/careers/search/"], sourceCheckedAt: "2026-09-20" },
  { id: "notion", company: "Notion", homepageUrl: "https://www.notion.so", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/notion" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Notion's first-party careers page links its roles to the Notion Ashby board.", sourceEvidenceUrls: ["https://www.notion.com/careers", "https://jobs.ashbyhq.com/notion"], sourceCheckedAt: "2026-09-20" },
  { id: "anthropic", company: "Anthropic", homepageUrl: "https://www.anthropic.com", expectedSource: { type: "greenhouse", url: "https://job-boards.greenhouse.io/anthropic" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Anthropic's first-party jobs listing links each live role to its Greenhouse board.", sourceEvidenceUrls: ["https://www.anthropic.com/careers", "https://www.anthropic.com/jobs", "https://job-boards.greenhouse.io/anthropic"], sourceCheckedAt: "2026-09-20" },
  { id: "netflix", company: "Netflix", homepageUrl: "https://www.netflix.com", expectedSource: { type: "eightfold", url: "https://netflix.eightfold.ai/careers", equivalentUrls: ["https://explore.jobs.netflix.net/careers"] }, expectedRoleCount: null, labelStatus: checked, labelNote: "Independently rechecked by the orchestration reviewer on 29 September: Netflix’s official careers landing page links View roles to explore.jobs.netflix.net/careers; netflix.eightfold.ai/careers redirects to that exact listing. The former jobs.netflix.com label was a landing page. This corrects source identity only, not posting coverage or automatic discovery quality.", sourceEvidenceUrls: ["https://jobs.netflix.com/", "https://explore.jobs.netflix.net/careers", "https://netflix.eightfold.ai/careers"], sourceCheckedAt: "2026-09-29" },
  { id: "figma", company: "Figma", homepageUrl: "https://www.figma.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/figma" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Figma's first-party careers page links its roles to the Figma Greenhouse board.", sourceEvidenceUrls: ["https://www.figma.com/careers/", "https://job-boards.greenhouse.io/figma"], sourceCheckedAt: "2026-09-20" },
  { id: "datadog", company: "Datadog", homepageUrl: "https://www.datadoghq.com", expectedSource: { type: "html", url: "https://careers.datadoghq.com/all-jobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Datadog's company-owned careers homepage explicitly links to All Jobs; that destination has its own canonical URL and is the complete searchable listing. The previous careers-root and Greenhouse candidates were landing/stale sources.", sourceEvidenceUrls: ["https://careers.datadoghq.com/", "https://careers.datadoghq.com/all-jobs/"], sourceCheckedAt: "2026-09-20", coverage: { customHtml: { evidenceUrl: "https://careers.datadoghq.com/all-jobs/", checkedAt: "2026-09-29", note: "Company-owned all-jobs HTML listing required custom pagination handling; retained browser capture in SOURCE-BROWSER-CAPTURE-REPORT.md." }, jsHeavy: { evidenceUrl: "https://careers.datadoghq.com/all-jobs/", checkedAt: "2026-09-29", note: "Static HTML omitted job rows; independent static-mount diagnostic and browser captures established client-rendered roles." } } },
  { id: "cloudflare", company: "Cloudflare", homepageUrl: "https://www.cloudflare.com", expectedSource: { type: "html", url: "https://www.cloudflare.com/careers/jobs/", equivalentSources: [{ type: "greenhouse", url: "https://job-boards.greenhouse.io/cloudflare" }] }, expectedRoleCount: null, labelStatus: checked, labelNote: "On 29 September, Cloudflare's first-party full listing requested its Greenhouse feed and displayed the same 402 exact posting URLs/IDs after all Load more clicks. The earlier stale-Greenhouse statement is superseded for this exact board; source identity equivalence does not qualify posting quality. Evidence: docs/reviews/2026-09-29/SOURCE-EQUIVALENCE-AUDIT.md.", sourceEvidenceUrls: ["https://www.cloudflare.com/careers/", "https://www.cloudflare.com/careers/jobs/", "https://boards-api.greenhouse.io/v1/boards/cloudflare/jobs", "https://job-boards.greenhouse.io/cloudflare"], sourceCheckedAt: "2026-09-29", coverage: { customHtml: { evidenceUrl: "https://www.cloudflare.com/careers/jobs/", checkedAt: "2026-09-29", note: "First-party jobs HTML uses a site-specific Load more control; retained rendered source comparison in SOURCE-EQUIVALENCE-AUDIT.md." }, jsHeavy: { evidenceUrl: "https://www.cloudflare.com/careers/jobs/", checkedAt: "2026-09-29", note: "Static HTML displayed Loading roles while browser rendering loaded the current roles; retained browser capture in SOURCE-BROWSER-CAPTURE-REPORT.md." } } },
  { id: "canonical", company: "Canonical", homepageUrl: "https://canonical.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/canonical" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Canonical's first-party careers page links its roles to the Canonical Greenhouse board.", sourceEvidenceUrls: ["https://canonical.com/careers", "https://job-boards.greenhouse.io/canonical"], sourceCheckedAt: "2026-09-20" },
  { id: "automattic", company: "Automattic", homepageUrl: "https://automattic.com", expectedSource: { type: "html", url: "https://automattic.com/work-with-us/jobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Automattic states that legitimate openings are published on its company-owned careers site; the previous Greenhouse board candidate was stale.", sourceEvidenceUrls: ["https://automattic.com/work-with-us/", "https://automattic.com/work-with-us/jobs/"], sourceCheckedAt: "2026-09-20" },
  { id: "gitlab", company: "GitLab", homepageUrl: "https://about.gitlab.com", expectedSource: { type: "greenhouse", url: "https://job-boards.greenhouse.io/gitlab" }, expectedRoleCount: null, labelStatus: checked, labelNote: "GitLab's first-party careers flow currently resolves its live openings through the GitLab Greenhouse board; the company-owned all-jobs page remains supporting evidence.", sourceEvidenceUrls: ["https://about.gitlab.com/jobs/", "https://about.gitlab.com/jobs/all-jobs/", "https://job-boards.greenhouse.io/gitlab"], sourceCheckedAt: "2026-09-20" },
  { id: "wise", company: "Wise", homepageUrl: "https://wise.com", expectedSource: { type: "html", url: "https://wise.jobs/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Wise's explicit first-party all-jobs listing is a SmartRecruiters Attrax-powered custom HTML site, not Workday or the SmartRecruiters public postings API.", sourceEvidenceUrls: ["https://wise.jobs", "https://wise.jobs/jobs"], sourceCheckedAt: "2026-09-20" },
  { id: "salesforce", company: "Salesforce", homepageUrl: "https://www.salesforce.com", expectedSource: { type: "html", url: "https://careers.salesforce.com/en/jobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Salesforce's company-owned careers site publishes its current searchable jobs listing; the previous Workday candidate was stale.", sourceEvidenceUrls: ["https://careers.salesforce.com/", "https://careers.salesforce.com/en/jobs/"], sourceCheckedAt: "2026-09-20" },
  { id: "siemens", company: "Siemens", homepageUrl: "https://www.siemens.com", expectedSource: { type: "html", url: "https://jobs.siemens.com/en_US/externaljobs/SearchJobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Siemens' company-owned Careers Marketplace publishes the searchable external-jobs listing; the previous Workday-shaped candidate was invalid.", sourceEvidenceUrls: ["https://jobs.siemens.com/", "https://jobs.siemens.com/en_US/externaljobs/SearchJobs/"], sourceCheckedAt: "2026-09-20", coverage: { customHtml: { evidenceUrl: "https://jobs.siemens.com/en_US/externaljobs/SearchJobs/", checkedAt: "2026-09-29", note: "Company-owned listing has custom six-role HTTP pagination; retained continuation audit observed distinct JobDetail links across 80 pages." } } },
  { id: "spotify", company: "Spotify", homepageUrl: "https://www.spotify.com", expectedSource: { type: "html", url: "https://www.lifeatspotify.com/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Spotify's first-party applicant guidance identifies lifeatspotify.com/jobs as its careers listing (and Lever only as a possible role-detail destination).", sourceEvidenceUrls: ["https://www.lifeatspotify.com/start-your-journey", "https://www.lifeatspotify.com/jobs"], sourceCheckedAt: "2026-09-20" },
  { id: "mozilla", company: "Mozilla", homepageUrl: "https://www.mozilla.org", expectedSource: { type: "html", url: "https://www.mozilla.org/en-US/careers/listings/", equivalentUrls: ["https://www.mozilla.org/en-GB/careers/listings/"] }, expectedRoleCount: null, labelStatus: checked, labelNote: "Mozilla's first-party careers page links to its company-owned job listing. The en-US and en-GB listing snapshots exposed the same complete set of posting identities on the review date.", sourceEvidenceUrls: ["https://www.mozilla.org/en-US/careers/", "https://www.mozilla.org/en-US/careers/listings/", "https://www.mozilla.org/en-GB/careers/listings/"], sourceCheckedAt: "2026-09-20", coverage: { customHtml: { evidenceUrl: "https://www.mozilla.org/en-GB/careers/listings/", checkedAt: "2026-09-29", note: "First-party HTML job listings have distinct posting links; retained page-signal diagnostic separates this listing from editorial careers links." } } },
  { id: "basecamp", company: "37signals", homepageUrl: "https://37signals.com", expectedSource: { type: "html", url: "https://37signals.com/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "37signals publishes current openings, including an explicit empty state, on its company-owned jobs page.", sourceEvidenceUrls: ["https://37signals.com/jobs"], sourceCheckedAt: "2026-09-20" },
  { id: "monzo", company: "Monzo", homepageUrl: "https://monzo.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/monzo" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Monzo's first-party careers page links to the Monzo Greenhouse board.", sourceEvidenceUrls: ["https://monzo.com/careers", "https://boards.greenhouse.io/monzo"], sourceCheckedAt: "2026-09-20" },
  { id: "revolut", company: "Revolut", homepageUrl: "https://www.revolut.com", expectedSource: { type: "html", url: "https://www.revolut.com/careers/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Revolut's company-owned careers page is the current searchable jobs listing; the previous Greenhouse board candidate was stale.", sourceEvidenceUrls: ["https://www.revolut.com/careers/"], sourceCheckedAt: "2026-09-20" },
  { id: "zapier", company: "Zapier", homepageUrl: "https://zapier.com", expectedSource: { type: "html", url: "https://zapier.com/jobs", equivalentSources: [{ type: "ashby", url: "https://jobs.ashbyhq.com/zapier" }] }, expectedRoleCount: null, labelStatus: checked, labelNote: "On 29 September, Zapier's first-party jobs page requested its Ashby feed and displayed the same 10 exact listed posting URLs/IDs. The earlier stale-board statement concerned Greenhouse, not this Ashby board; source identity equivalence does not qualify posting quality. Evidence: docs/reviews/2026-09-29/SOURCE-EQUIVALENCE-AUDIT.md.", sourceEvidenceUrls: ["https://zapier.com/jobs", "https://api.ashbyhq.com/posting-api/job-board/zapier", "https://jobs.ashbyhq.com/zapier"], sourceCheckedAt: "2026-09-29" },
  { id: "linear", company: "Linear", homepageUrl: "https://linear.app", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/Linear" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Linear's first-party careers listing links its roles to the Linear Ashby board.", sourceEvidenceUrls: ["https://linear.app/careers", "https://jobs.ashbyhq.com/Linear"], sourceCheckedAt: "2026-09-20" },
  { id: "vercel", company: "Vercel", homepageUrl: "https://vercel.com", expectedSource: { type: "greenhouse", url: "https://job-boards.greenhouse.io/vercel" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Vercel's first-party careers page links its roles to the Vercel Greenhouse board; the earlier Ashby candidate was stale.", sourceEvidenceUrls: ["https://vercel.com/careers", "https://job-boards.greenhouse.io/vercel"], sourceCheckedAt: "2026-09-20" },
  { id: "render", company: "Render", homepageUrl: "https://render.com", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/render" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Render's first-party careers page links its roles to the Render Ashby board.", sourceEvidenceUrls: ["https://render.com/careers", "https://jobs.ashbyhq.com/render"], sourceCheckedAt: "2026-09-20" },
  { id: "shieldai", company: "Shield AI", homepageUrl: "https://shield.ai", expectedSource: { type: "lever", url: "https://jobs.lever.co/shieldai" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Checked 1 October: the Shield AI careers page links its own Open Roles to this Lever board. The separate Aechelon Roles link is a different scope; this is source identity only, without human posting labels.", sourceEvidenceUrls: ["https://shield.ai/careers/", "https://jobs.lever.co/shieldai"], sourceCheckedAt: "2026-10-01", coverage: { landingToExternalBoard: { evidenceUrl: "https://shield.ai/careers/", checkedAt: "2026-10-01", note: "The first-party Shield AI careers landing page links Open Roles to its distinct jobs.lever.co/shieldai board; Aechelon is separately linked." } } },
  { id: "trailofbits", company: "Trail of Bits", homepageUrl: "https://www.trailofbits.com", expectedSource: { type: "workable", url: "https://apply.workable.com/trailofbits/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Checked 1 October: the first-party careers page links View all jobs to the Trail of Bits Workable board. This establishes source identity only, not a human-reviewed posting count.", sourceEvidenceUrls: ["https://www.trailofbits.com/careers", "https://apply.workable.com/trailofbits/"], sourceCheckedAt: "2026-10-01" },
  { id: "chip", company: "Chip", homepageUrl: "https://getchip.uk", expectedSource: { type: "teamtailor", url: "https://chip.teamtailor.com/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Checked 1 October: Chip's first-party homepage links Careers to chip.teamtailor.com, whose All jobs control opens the unfiltered /jobs listing. Source identity only; current roles have no human labels.", sourceEvidenceUrls: ["https://getchip.uk/", "https://chip.teamtailor.com/", "https://chip.teamtailor.com/jobs"], sourceCheckedAt: "2026-10-01" },
  { id: "3m", company: "3M", homepageUrl: "https://www.3m.com", expectedSource: { type: "workday", url: "https://3m.wd1.myworkdayjobs.com/en-US/Search" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Checked 1 October: 3M's first-party US careers page links Search Jobs to this Workday board. A separate unfiltered first-page public board response showed postings in multiple countries; no full-board posting count or recall has been qualified.", sourceEvidenceUrls: ["https://www.3m.com/3M/en_US/careers-us/", "https://3m.wd1.myworkdayjobs.com/en-US/Search", "https://3m.wd1.myworkdayjobs.com/wday/cxs/3m/Search/jobs"], sourceCheckedAt: "2026-10-01", coverage: { multiRegionWorkday: { evidenceUrl: "https://3m.wd1.myworkdayjobs.com/wday/cxs/3m/Search/jobs", checkedAt: "2026-10-01", note: "Unfiltered first-page public Workday response includes postings in the US, France, Vietnam, India, Mexico and Belgium; retained in implementation-evidence/workday-region/3m-page.json." } } },
  { id: "workday", company: "Workday", homepageUrl: "https://www.workday.com", expectedSource: { type: "workday", url: "https://workday.wd5.myworkdayjobs.com/Workday/?source=Careers_Website" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Checked 1 October: Workday's first-party careers page links Job Search to this Workday board. A separate unfiltered first-page public board response showed postings in multiple countries; no full-board posting count or recall has been qualified.", sourceEvidenceUrls: ["https://www.workday.com/en-us/company/careers/overview.html", "https://workday.wd5.myworkdayjobs.com/Workday/?source=Careers_Website", "https://workday.wd5.myworkdayjobs.com/wday/cxs/workday/Workday/jobs"], sourceCheckedAt: "2026-10-01", coverage: { multiRegionWorkday: { evidenceUrl: "https://workday.wd5.myworkdayjobs.com/wday/cxs/workday/Workday/jobs", checkedAt: "2026-10-01", note: "Unfiltered first-page public Workday response includes postings in Costa Rica, Ireland, the US and Canada; retained in implementation-evidence/workday-region/workday-page.json." } } },
  { id: "r2", company: "R2", homepageUrl: "https://r2.co", expectedSource: { type: "bamboohr", url: "https://r2.bamboohr.com/careers" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Checked 1 October: R2's first-party homepage Careers link opens its unfiltered BambooHR board. The text reader saw a JavaScript shell, so this establishes source identity only, not a human posting label or extraction quality.", sourceEvidenceUrls: ["https://r2.co/", "https://r2.bamboohr.com/careers"], sourceCheckedAt: "2026-10-01" },
];
