import type { LiveAcceptanceCase } from "./live-acceptance";

const checked = "source_independently_checked" as const;

/**
 * Representative public boards. Source labels are review inputs, not observations made by the
 * harness. Role counts deliberately remain null until a person counts a dated snapshot.
 */
export const LIVE_ACCEPTANCE_CASES: LiveAcceptanceCase[] = [
  { id: "anduril", company: "Anduril", homepageUrl: "https://www.anduril.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/andurilindustries" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Board mapping is documented in REVIEW-PLAN; current count is time-dependent.", sourceEvidenceUrls: ["https://www.anduril.com/careers", "https://job-boards.greenhouse.io/andurilindustries"], sourceCheckedAt: "2026-09-20" },
  { id: "airbnb", company: "Airbnb", homepageUrl: "https://www.airbnb.com", expectedSource: { type: "html", url: "https://careers.airbnb.com/positions/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Airbnb's first-party careers homepage links to its company-owned all-jobs listing; the previous Greenhouse board candidate was stale.", sourceEvidenceUrls: ["https://careers.airbnb.com/", "https://careers.airbnb.com/positions/"], sourceCheckedAt: "2026-09-20" },
  { id: "stripe", company: "Stripe", homepageUrl: "https://stripe.com", expectedSource: { type: "html", url: "https://stripe.com/careers/search" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Stripe's first-party careers page links to its current searchable listing at /careers/search; the previous Greenhouse board and /jobs/search candidates were stale.", sourceEvidenceUrls: ["https://stripe.com/careers", "https://stripe.com/careers/search"], sourceCheckedAt: "2026-09-20" },
  { id: "openai", company: "OpenAI", homepageUrl: "https://openai.com", expectedSource: { type: "html", url: "https://openai.com/careers/search/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "OpenAI's first-party careers page links to its first-party search listing; the previous Ashby candidate was stale.", sourceEvidenceUrls: ["https://openai.com/careers/", "https://openai.com/careers/search/"], sourceCheckedAt: "2026-09-20" },
  { id: "notion", company: "Notion", homepageUrl: "https://www.notion.so", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/notion" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Notion's first-party careers page links its roles to the Notion Ashby board.", sourceEvidenceUrls: ["https://www.notion.com/careers", "https://jobs.ashbyhq.com/notion"], sourceCheckedAt: "2026-09-20" },
  { id: "anthropic", company: "Anthropic", homepageUrl: "https://www.anthropic.com", expectedSource: { type: "greenhouse", url: "https://job-boards.greenhouse.io/anthropic" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Anthropic's first-party jobs listing links each live role to its Greenhouse board.", sourceEvidenceUrls: ["https://www.anthropic.com/careers", "https://www.anthropic.com/jobs", "https://job-boards.greenhouse.io/anthropic"], sourceCheckedAt: "2026-09-20" },
  { id: "netflix", company: "Netflix", homepageUrl: "https://www.netflix.com", expectedSource: { type: "html", url: "https://jobs.netflix.com/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Netflix publishes and links its open-role search on its company-owned careers site; the previous Lever candidate was stale.", sourceEvidenceUrls: ["https://jobs.netflix.com/"], sourceCheckedAt: "2026-09-20" },
  { id: "figma", company: "Figma", homepageUrl: "https://www.figma.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/figma" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Figma's first-party careers page links its roles to the Figma Greenhouse board.", sourceEvidenceUrls: ["https://www.figma.com/careers/", "https://job-boards.greenhouse.io/figma"], sourceCheckedAt: "2026-09-20" },
  { id: "datadog", company: "Datadog", homepageUrl: "https://www.datadoghq.com", expectedSource: { type: "html", url: "https://careers.datadoghq.com/all-jobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Datadog's company-owned careers homepage explicitly links to All Jobs; that destination has its own canonical URL and is the complete searchable listing. The previous careers-root and Greenhouse candidates were landing/stale sources.", sourceEvidenceUrls: ["https://careers.datadoghq.com/", "https://careers.datadoghq.com/all-jobs/"], sourceCheckedAt: "2026-09-20" },
  { id: "cloudflare", company: "Cloudflare", homepageUrl: "https://www.cloudflare.com", expectedSource: { type: "html", url: "https://www.cloudflare.com/careers/jobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Cloudflare's first-party careers page links to its company-owned open-positions listing; the previous Greenhouse board candidate was stale.", sourceEvidenceUrls: ["https://www.cloudflare.com/careers/", "https://www.cloudflare.com/careers/jobs/"], sourceCheckedAt: "2026-09-20" },
  { id: "canonical", company: "Canonical", homepageUrl: "https://canonical.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/canonical" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Canonical's first-party careers page links its roles to the Canonical Greenhouse board.", sourceEvidenceUrls: ["https://canonical.com/careers", "https://job-boards.greenhouse.io/canonical"], sourceCheckedAt: "2026-09-20" },
  { id: "automattic", company: "Automattic", homepageUrl: "https://automattic.com", expectedSource: { type: "html", url: "https://automattic.com/work-with-us/jobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Automattic states that legitimate openings are published on its company-owned careers site; the previous Greenhouse board candidate was stale.", sourceEvidenceUrls: ["https://automattic.com/work-with-us/", "https://automattic.com/work-with-us/jobs/"], sourceCheckedAt: "2026-09-20" },
  { id: "gitlab", company: "GitLab", homepageUrl: "https://about.gitlab.com", expectedSource: { type: "greenhouse", url: "https://job-boards.greenhouse.io/gitlab" }, expectedRoleCount: null, labelStatus: checked, labelNote: "GitLab's first-party careers flow currently resolves its live openings through the GitLab Greenhouse board; the company-owned all-jobs page remains supporting evidence.", sourceEvidenceUrls: ["https://about.gitlab.com/jobs/", "https://about.gitlab.com/jobs/all-jobs/", "https://job-boards.greenhouse.io/gitlab"], sourceCheckedAt: "2026-09-20" },
  { id: "wise", company: "Wise", homepageUrl: "https://wise.com", expectedSource: { type: "html", url: "https://wise.jobs/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Wise's explicit first-party all-jobs listing is a SmartRecruiters Attrax-powered custom HTML site, not Workday or the SmartRecruiters public postings API.", sourceEvidenceUrls: ["https://wise.jobs", "https://wise.jobs/jobs"], sourceCheckedAt: "2026-09-20" },
  { id: "salesforce", company: "Salesforce", homepageUrl: "https://www.salesforce.com", expectedSource: { type: "html", url: "https://careers.salesforce.com/en/jobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Salesforce's company-owned careers site publishes its current searchable jobs listing; the previous Workday candidate was stale.", sourceEvidenceUrls: ["https://careers.salesforce.com/", "https://careers.salesforce.com/en/jobs/"], sourceCheckedAt: "2026-09-20" },
  { id: "siemens", company: "Siemens", homepageUrl: "https://www.siemens.com", expectedSource: { type: "html", url: "https://jobs.siemens.com/en_US/externaljobs/SearchJobs/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Siemens' company-owned Careers Marketplace publishes the searchable external-jobs listing; the previous Workday-shaped candidate was invalid.", sourceEvidenceUrls: ["https://jobs.siemens.com/", "https://jobs.siemens.com/en_US/externaljobs/SearchJobs/"], sourceCheckedAt: "2026-09-20" },
  { id: "spotify", company: "Spotify", homepageUrl: "https://www.spotify.com", expectedSource: { type: "html", url: "https://www.lifeatspotify.com/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Spotify's first-party applicant guidance identifies lifeatspotify.com/jobs as its careers listing (and Lever only as a possible role-detail destination).", sourceEvidenceUrls: ["https://www.lifeatspotify.com/start-your-journey", "https://www.lifeatspotify.com/jobs"], sourceCheckedAt: "2026-09-20" },
  { id: "mozilla", company: "Mozilla", homepageUrl: "https://www.mozilla.org", expectedSource: { type: "html", url: "https://www.mozilla.org/en-US/careers/listings/", equivalentUrls: ["https://www.mozilla.org/en-GB/careers/listings/"] }, expectedRoleCount: null, labelStatus: checked, labelNote: "Mozilla's first-party careers page links to its company-owned job listing. The en-US and en-GB listing snapshots exposed the same complete set of posting identities on the review date.", sourceEvidenceUrls: ["https://www.mozilla.org/en-US/careers/", "https://www.mozilla.org/en-US/careers/listings/", "https://www.mozilla.org/en-GB/careers/listings/"], sourceCheckedAt: "2026-09-20" },
  { id: "basecamp", company: "37signals", homepageUrl: "https://37signals.com", expectedSource: { type: "html", url: "https://37signals.com/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "37signals publishes current openings, including an explicit empty state, on its company-owned jobs page.", sourceEvidenceUrls: ["https://37signals.com/jobs"], sourceCheckedAt: "2026-09-20" },
  { id: "monzo", company: "Monzo", homepageUrl: "https://monzo.com", expectedSource: { type: "greenhouse", url: "https://boards.greenhouse.io/monzo" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Monzo's first-party careers page links to the Monzo Greenhouse board.", sourceEvidenceUrls: ["https://monzo.com/careers", "https://boards.greenhouse.io/monzo"], sourceCheckedAt: "2026-09-20" },
  { id: "revolut", company: "Revolut", homepageUrl: "https://www.revolut.com", expectedSource: { type: "html", url: "https://www.revolut.com/careers/" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Revolut's company-owned careers page is the current searchable jobs listing; the previous Greenhouse board candidate was stale.", sourceEvidenceUrls: ["https://www.revolut.com/careers/"], sourceCheckedAt: "2026-09-20" },
  { id: "zapier", company: "Zapier", homepageUrl: "https://zapier.com", expectedSource: { type: "html", url: "https://zapier.com/jobs" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Zapier's company-owned jobs page links its current openings; the previous Greenhouse board candidate was stale.", sourceEvidenceUrls: ["https://zapier.com/jobs"], sourceCheckedAt: "2026-09-20" },
  { id: "linear", company: "Linear", homepageUrl: "https://linear.app", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/Linear" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Linear's first-party careers listing links its roles to the Linear Ashby board.", sourceEvidenceUrls: ["https://linear.app/careers", "https://jobs.ashbyhq.com/Linear"], sourceCheckedAt: "2026-09-20" },
  { id: "vercel", company: "Vercel", homepageUrl: "https://vercel.com", expectedSource: { type: "greenhouse", url: "https://job-boards.greenhouse.io/vercel" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Vercel's first-party careers page links its roles to the Vercel Greenhouse board; the earlier Ashby candidate was stale.", sourceEvidenceUrls: ["https://vercel.com/careers", "https://job-boards.greenhouse.io/vercel"], sourceCheckedAt: "2026-09-20" },
  { id: "render", company: "Render", homepageUrl: "https://render.com", expectedSource: { type: "ashby", url: "https://jobs.ashbyhq.com/render" }, expectedRoleCount: null, labelStatus: checked, labelNote: "Render's first-party careers page links its roles to the Render Ashby board.", sourceEvidenceUrls: ["https://render.com/careers", "https://jobs.ashbyhq.com/render"], sourceCheckedAt: "2026-09-20" },
];
