// Generated by `pnpm exec tsx scripts/check-evaluation-reports.ts --write` from the committed evaluation
// report named below; CI fails when it no longer matches. Do not edit by hand.
import type { EvaluatedRoutes } from "./stage-route-drift";

/** The route each CV stage was graded at in the last committed evaluation report. */
export const EVALUATED_ROUTES: EvaluatedRoutes = {
  "report": "docs/evaluations/cv-replay/report.json",
  "promptSetVersion": "914bd3e6aae5",
  "unverified": true,
  "at": "2026-09-26T11:29:53.957Z",
  "routes": {
    "cv.author": {
      "model": "cvModel",
      "resolvedModel": "claude-fable-5-1",
      "effort": "high",
      "defaultModel": "cvModel",
      "defaultEffort": "high"
    },
    "cv.improvement": {
      "model": "cvModel",
      "resolvedModel": "claude-fable-5-1",
      "effort": "high",
      "defaultModel": "cvModel",
      "defaultEffort": "high"
    },
    "cv.planning": {
      "model": "cvModel",
      "resolvedModel": "claude-fable-5-1",
      "effort": "high",
      "defaultModel": "cvModel",
      "defaultEffort": "high"
    },
    "cv.review": {
      "model": "cvModel",
      "resolvedModel": "claude-fable-5-1",
      "effort": "high",
      "defaultModel": "cvModel",
      "defaultEffort": "high"
    },
    "cv.review_candidate": {
      "model": "cvModel",
      "resolvedModel": "claude-fable-5-1",
      "effort": "high",
      "defaultModel": "cvModel",
      "defaultEffort": "high"
    },
    "cv.rubric": {
      "model": "cvModel",
      "resolvedModel": "claude-fable-5-1",
      "effort": "high",
      "defaultModel": "cvModel",
      "defaultEffort": "high"
    }
  }
};
